origin_of_local_coordinate_system_x_wgs84 = 6.5668
origin_of_local_coordinate_system_y_wgs84 = 46.5191
origin_of_local_coordinate_system_z_wgs84 = 390
crossloc_pose_result_folder = 'C:\\projects\\vnav\\topo-vnav-ml-challenge\\data_challenge_preparation\\data_sample\\from_crossloc'

# parameters for crossloc_output_2_csv.py
pose_gt_file_name = 'pose_gt.npy'
path_file_out_gt = 'C:\\projects\\vnav\\topo-vnav-ml-challenge\\data_challenge_preparation\\data_sample\\output\\gt.csv'
pose_pred_file_name = 'pose_pred.npy'
path_file_out_pred = 'C:\\projects\\vnav\\topo-vnav-ml-challenge\\data_challenge_preparation\\data_sample\\output\\pred.csv'

# parameters for pose_2_csv.py and csv_2_pose.py
path_folder_poses_txt = 'C:\projects\vnav\data\challenge\ready_for_publishing\urbanscape\validation_ground_truth\drone_val_sim\poses'
path_file_poses_csv = 'C:\projects\vnav\topo-vnav-ml-challenge\data_challenge_preparation\data_sample\output\gt.csv'

# parameter for evaluation.py
path_csv_ground_truth = 'C:\projects\vnav\topo-vnav-ml-challenge\codalab_bundle\reference_data\gt.csv'
path_csv_estimation = 'C:\projects\vnav\topo-vnav-ml-challenge\data_challenge_preparation\data_sample\output\est.csv'
u_val_tranlation = 1
u_val_rotation = 1
uncertainty_on_coordinates_min_range = 0.3
uncertainty_on_coordinates_max_range = 1
uncertainty_on_angles_min_range = 0.3
uncertainty_on_angles_max_range = 1